project:
  type: website

website:
  navbar: 
    search: true
    left:
      - text: "Home"
        href: home/index.qmd
      - text: "Lectures"
        href: lectures/lectures.qmd
      - text: "Exercises"
        href: exercises/exercises.qmd  
  title: "Reproducible Data Visualisation with R"
  
  sidebar:
    - title: "Home"
      style: "floating"
      contents:
        - home/index.qmd
    - title: "Lectures"
      style: "floating"
      contents:
        - lectures/lectures.qmd
        - lectures/lecture1.qmd
        - lectures/lecture2.qmd  
    - title: "Exercises"
      style: "floating"
      contents:
        - exercises/exercises.qmd
        - exercises/exercise1.qmd
        - exercises/exercise2.qmd
      
format:
  html:
    theme:
      light: litera
      dark: cyborg
    css: custom.scss
    toc: true

execute:
  freeze: auto
  cache: true


