project:
  type: website
  output-dir: docs
website:
  title: Data Viz with R
  page-navigation: true
  favicon: images/favicon.ico
  navbar: 
    search: true
    left:
      - text: "Home"
        href: home/index.qmd
        icon: house-fill
      - text: "Lectures"
        href: lectures/overview.qmd
        icon: easel3-fill
      - text: "Exercises"
        href: exercises/overview.qmd  
        icon: code-slash

  sidebar:
      style: "floating"
      collape-level: 1
      contents:
        - section: "Home"
          contents:
          - text: "Schedule"
            href: home/index.qmd
          - text: "Prerequisites"
            href: home/prerequisites.qmd
          - text: "Approach"
            href: home/approach.qmd
          - text: "Orientation"
            href: home/orientation.qmd
        - text: "Lectures"
          href: lectures/overview.qmd
        - section: "Exercises"
          contents:
            - text: Overview
              href: exercises/overview.qmd
            - section: "Day 1. Data cleaning"
              contents:
              - section: "Exercise 1 (Beginner)"
                contents:
                  - exercises/exercise1-1.qmd
                  - exercises/exercise1-2.qmd
              - section: "Exercise 2 (Advanced)"
                contents:
                  - exercises/exercise2-1.qmd
                  - exercises/exercise2-2.qmd
            - section: "Day 2. Visualisation"
              contents:
              - section: "Exercise 3 (Beginner)"
                contents:
                  - exercises/exercise3-1.qmd
                  - section: "Step-by-step guide"
                    contents:
                    - exercises/exercise3-2.qmd
                    - exercises/exercise3-3.qmd
                    - exercises/exercise3-4.qmd
                    - exercises/exercise3-5.qmd
              - section: "Exercise 4 (Advanced)"
                contents:
                  - exercises/exercise4-1.qmd
                  - exercises/exercise4-2.qmd            
format:
  html:
    theme:
      light: litera
      dark: cyborg
    css: custom.scss
    toc: true
    code-copy: true
filters:
  - line-highlight

crossref:
  custom:
    - kind: float
      reference-prefix: ☠ Hint
      key: hint

execute:
  freeze: auto
  cache: true


