project:
  type: website
  output-dir: docs
website:
  title: Data Viz with R
  page-navigation: true
  favicon: images/favicon.ico
  navbar: 
    search: true
    left:
      - text: "Home"
        href: home/index.qmd
        icon: house-fill
      - text: "Lectures"
        href: lectures/lectures.qmd
        icon: easel3-fill
      - text: "Exercises"
        href: exercises/overview.qmd  
        icon: code-slash

  sidebar:
      style: "floating"
      collape-level: 1
      title: Orientation
      contents:
        - text: "Orientation"
          href: home/index.qmd
        - section: "Lectures"
          contents:
            - lectures/lectures.qmd
            - lectures/lecture1.qmd
            - lectures/lecture2.qmd  
        - section: "Exercises"
          contents:
            - section: "Data cleaning"
              contents:
              - text: Overview
                href: exercises/overview.qmd
              - section: "Exercise 1"
                contents:
                  - exercises/exercise1-1.qmd
                  - exercises/exercise1-2.qmd
              - section: "Exercise 2"
                contents:
                  - exercises/exercise2-1.qmd
                  - exercises/exercise2-2.qmd
            - section: "Visualisation"
              contents:
              - text: Overview
                href: exercises/overview.qmd
              - section: "Exercise 3"
                contents:
                  - exercises/exercise3-1.qmd
                  - section: "Step-by-step guide"
                    contents:
                    - exercises/exercise3-2.qmd
                    - exercises/exercise3-3.qmd
                    - exercises/exercise3-4.qmd
              - section: "Exercise 4"
                contents:
                  - exercises/exercise4-1.qmd
                  - exercises/exercise4-2.qmd            
format:
  html:
    theme:
      light: litera
      dark: cyborg
    css: custom.scss
    toc: true
    code-copy: true
filters:
  - line-highlight

crossref:
  custom:
    - kind: float
      reference-prefix: ☠ Hint
      key: hint

execute:
  freeze: auto
  cache: true


